curators:
 - alexellis
 - welteki
 - Jasstkn

features:
 - dco_check
 - comments
 - pr_description_required
 - release_notes

contributing_url: https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md
